### ISSUE TITLE
pluck does not exist on QueryParams/RouteParams?

### ISSUE THREAD

**Issue by qdouble** [ngrx/router#101]
I'm getting this error and can't figure out why:
`[default] /Users/qdouble/Sites/MAIN_PROJECT/offersystem-frontend/src/app/components/blog-page.ts:20:29 
    Property 'pluck' does not exist on type 'RouteParams'.`

```
import {Component} from '@angular/core';
import { RouteParams } from '@ngrx/router';
import { Observable } from 'rxjs/Observable';


@Component({
  selector: 'blog-page',
  template: `
  
  <h3>This is a blog.</h3> 
  <route-view></route-view>
  
  `
})

export class Blog {
  id$: Observable<string>;

  constructor(routeParams$: RouteParams) {
    this.id$ = routeParams$.pluck('id');
  }
```
My IDE also says that pluck is an unresolved method or function. 
I have "@ngrx/router": "0.4.1" installed.

**Comment by fxck** [comment]
```
import 'rxjs/add/operator/pluck';

```

**Comment by qdouble** [comment]
@fxck thanks... it compiles now, but my IDEs still complain
VSCode underlines **this.id$** and shows: 

> [ts] Type 'Observable<{}>' is not assignable to type 'Observable<string>'. Type '{}' is not assignable to type 'string'.
>(property) Blog.id$: Observable<string>

while Webstorm will give `Unresolved function or method pluck()`

any hints on getting rid of IDE errors/warnings?

**Comment by brandonroberts** [comment]
You'll need to type the explicitly type the pluck: See https://github.com/ngrx/router/issues/95
