### ISSUE TITLE
Do all routes need to be passed for bootstraping?

### ISSUE THREAD

**Issue by jeserkin** [ngrx/router#105]
Do all routes need to be gathered in one place or it can be distributed like with angular2 router?

**Comment by laurelnaiad** [comment]
You can use the the optional loadChildren property of a route definition to lazy-load child route definitions from within any route configuration. The function should return a promise of an array of routes.

https://github.com/ngrx/router/blob/master/docs/overview/code-splitting.md (`loadChildren` doesn't get much press)

**Comment by jeserkin** [comment]
Okay. But are those exported `const`s passed somewhere further, like to provider for registration?

**Comment by laurelnaiad** [comment]
I don't know if I really understand what you're asking about, but whatever you pass to the provideRouter function becomes your routes. If some of them and/or some of their components are loaded lazily, that's fine, but it all stems from the object you pass as the routes to the provideRouter function.
