### ISSUE TITLE
typing route in URL bar

### ISSUE THREAD

**Issue by mckennatim** [ngrx/router#109]
I did the basic install and `linkTo` worked fine as did the back button. But when I typed into the url bar of the browser I get a "The requested URL ... was not found on this server. What would I need to do to get that functionality in a modern browser

    import {bootstrap}    from '@angular/platform-browser-dynamic'
    import { provideRouter, Routes } from '@ngrx/router';
    import {AppComponent} from './app.component'
    import {HelpComponent} from './help/help.component'
    import {AboutComponent} from './about/about.component'
    const routes: Routes = [
      { path: '/', component: AboutComponent },
      { path: '/about', component: AboutComponent },
      { path: '/help', component: HelpComponent }
    ]
    bootstrap(AppComponent, [provideRouter(routes)]);

**Comment by brandonroberts** [comment]
@mckennatim This normally depends on your server setup. The default is HTML5 mode, which requires that your server be setup to return your index.html file for all requests that would result in a 404. If you don't want the additional requirement, you can use the HashLocationStrategy instead.

**Comment by mckennatim** [comment]
thanks, `provide(LocationStrategy, { useClass: HashLocationStrategy })` works.

But you would think that webpack-dev-server would support HTML5 mode. Is there some flag to set that you know of?

**Comment by mckennatim** [comment]
adding this to webpack.config.js 

    devServer: {
      contentBase: "/wamp/www/ng2/sb/ng2-js-webp-broke-rt",
      historyApiFallback: true
    },    

does two things
1. causes page refresh if you type in the url bar
2. forgets to remove the prior path when you go back to linkTo buttons

localhost:6100/about
then press linkTo button for /help and you get
localhost:6100/about/help instead of localhost:6100/help

Oy I guess I need to go back to #

**Comment by brandonroberts** [comment]
When setup correctly, webpack-dev-server handles HTML5 mode works fine. You may need to add the `outputPath` to your webpack config.

**Comment by mckennatim** [comment]
Even then localhost WAMP doesn't work, and who knows if NGINX will.  I'll use hash routing til HTML 5 mode is easier. Thanks
