### ISSUE TITLE
Dispatching of events via route configuration

### ISSUE THREAD

**Issue by jhuntoo** [ngrx/router#111]
I'm not sure if this would be a good idea or not, if feel like this suggestion may violate the recommended practice of only dispatching events via services. But hear me out.

I'm in a situation where navigating to a route like /todos/new changes state by initialising a new Todo.
```ts
@Injectable()
export class TodosService {
  newTodo: Observable<Todo>;
  constructor(private store: Store<IAppState>) {
    this.newTodo =  newTodoSelector(store);
  }
  addNewTodo(): void {
    this.store.dispatch({ type: ADD_TODO_REQUEST});
  }
}

export class NewTodoPage {
  todo: Observable<Todo>;
  constructor(private todoService: TodoService) {
     todoService.addNewTodo();
     this.todo = todoService.newTodo;
  }
}
```

A convenient way to achieve this could be via Route config.
```ts
export const todoRoutes: Routes = [
  {
    path: '/todos/new',
    component: NewTodoPage,
    dispatch: { type: ADD_TODO_REQUEST}
  }
];
```

This would mean one less method on the service, and no DI is required on the Page component. Would that be bad practice ??

**Comment by brandonroberts** [comment]
I think this is just the type of scenario @MikeRyan52 wants to support. Something like this could be combined with `store-saga` which is becoming `ngrx/effects`.

**Comment by fxck** [comment]
You might want to do this with guards though(which is in this case unfortunate naming)..Since you might need stuff like id from params in the payload anyway.

**Comment by akomm** [comment]
What if you have same situation but one requires payload, other not. Would you mix, placing same type of triggers in route and outside? Would this not be confusing?

Services are good, because they can get different dependencies injected and so they can provide payload.
