### ISSUE TITLE
Defining an "otherwise" route fails to redirect

### ISSUE THREAD

**Issue by dballance** [ngrx/router#113]
**Steps to reproduce and a minimal demo of the problem**
http://plnkr.co/edit/b6dkMFAIRpNHepDDP4l0?p=preview

Open plunk -- notice that path is not redirected to '/home'

**Current behavior**
Per a previous gitter conversation, you can specify a "default" route by using: 
```
 { path: ‘/**’, redirectTo: ‘/home’ }
```
However this appears to be broken in 1.0.0-beta.1

**Expected/desired behavior**
A route path could be added as a catch all, and force a redirect to specified path. Similar to the "otherwise" functionality from angular-ui-router.

https://github.com/angular-ui/ui-router/blob/1e46c8d/src/urlRouter.js#L102

**Other information**
Workaround is available by redirecting the '/' route. 

```
export const routes = [
  {
    path: '/',
    redirectTo: '/home'
  },  
  {
    path: '/home',
    component: Home
  },
  {
    path: '/away',
    component: Away
  },
  {
    path: '/level1',
    component: Level1,
    index: {
      component: Level1Home
    }
  },
  {
    path: '/**',
    redirectTo: '/home'
  },    
];
```

**Comment by MikeRyan52** [comment]
Confirmed. You said as of beta 1, is this a regression in your app?

**Comment by dballance** [comment]
I haven't used previous versions, just trying to be explicit with the version I was using.

**Comment by ulfryk** [comment]
I had same issue
