### ISSUE TITLE
Why does not changing a param cause a page refresh?

### ISSUE THREAD

**Issue by mckennatim** [ngrx/router#123]
`http://localhost:6100/#/mqtt/subsys/tem3 ` will produce an output of `tem3 aval component` and I can type `tem4` in the url bar and it will update without a refresh but if I retype `tem3` again instead then a refresh happens. 

    import {Component} from '@angular/core';
    import { RouteParams } from '@ngrx/router';
    import { Observable } from 'rxjs/Observable';
    @Component({
        selector: 'aval',
        template: `<h3>{{ id$ | async }} {{me}}</h3>
        <route-view></route-view>`
    })
    export class AvalComponent {
      public me: string = "aval component";
      id$: Observable<any>; 
      constructor(routeParams$: RouteParams) {
        this.id$= routeParams$.pluck('id')
      }
    }

Where I am headed here is wanting to use the param to filter the store.

**Comment by MikeRyan52** [comment]
If you want to use the param to filter store, then I recommend using the `switchMap` operator. This will map the `id` into a new observable and listen to this observable until `id` updates again.

Here's a quick example:
```ts
this.user$ = routeParams$
  .pluck<string>('id')
  .switchMap(id => store.select(s => s.users[id]))
```

**Comment by mckennatim** [comment]
That is very cool. Now my plumbing is in place.
Is this typescript error easy to fix: 
`(20,40): error TS2342: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.` Line 20 is the `swtchMap` line. Not sure if it doesn't like `s` or `id` or ...

BTW It still does the refresh if you type in the same thing.

**Comment by mckennatim** [comment]
Adding toString() to `.switchMap(id => _store.select(s => s.mqtt[id.toString()]))` makes the error go away. Wonder what type comes back with `pluck('id'). Wonder how to find out.

**Comment by brandonroberts** [comment]
The type that comes back with just `pluck('id')` is an object. See #95
