### ISSUE TITLE
Components cache/reuse for previously visited routes

### ISSUE THREAD

**Issue by sergey-koretsky** [ngrx/router#125]
Hi, there is some interesting problem have been discussed for a while:
lets say we use "Tabs" design pattern where each of separate "Tab" is managed by a NG2 router, i.e.

"Tab1 " | "Tab2 "
with  /#/tab1 and /#/tab2 routes
where **Tab1Component** controls Tab1 and so on

so when a user clicks **Tab1** than **Tab2** and after he backs to **Tab1**, the **Tab1Component** would be totally recreated.
In that case when we have really heavy UI with different massive controls (Grids, graphs a lot of ajax requests for them etc) i think that to recreate the component each time a user clicks some different tab and backs again is really expensive.

you can find more examples and use cases for this Tab-approach here:
- http://stackoverflow.com/questions/34925782/angular2-routing-persisting-route-tabs-and-child-routes
- https://github.com/angular/angular/issues/6634
- https://github.com/angular/angular/issues/7757
- https://github.com/angular/angular/issues/5275
- https://github.com/angular/angular/issues/7965

so the question is: **does NGRX Router has some component reuse/cache mechanism, how to use it and will You intend to add this in the future**?

**Comment by michalstepien** [comment]
I'm trying to write their own implementation RouteView that will not take away components. I know it's naive solution. First, I use hidden to hide the component (Input - canDestroy). Second I swapped @Attribute ('name') private _name string on @Input. so to add dynamically named routerview. Thirdly I added canReuse to create once again a component and not to use the previous instance.
`/**
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/switchMap';
import {
    Component,
    ComponentRef,
    ReflectiveInjector,
    Inject,
    Injector,
    OnDestroy,
    OnInit,
    ViewContainerRef,
    Attribute,
    Provider,
    Input
} from '@angular/core';

import { Observable } from 'rxjs/Observable';
import { RouteParams, Router} from '@ngrx/router';
import { getNamedComponents, Route } from '@ngrx/router/route';

import { RouterInstruction } from '@ngrx/router/router-instruction';
import { ComponentRenderer } from '@ngrx/router/component-renderer';
import { Match } from '@ngrx/router/route-traverser';

import { RoutingService } from './routing.service';

@Component({
    selector: 'galactica-route-view',
    providers: [],
    template: ``
})
export class GalacticaRouteView implements OnDestroy, OnInit {
    private _prev: ComponentRef<any>;
    private _sub: any;
    private _routerInstructionProvider = new Provider(RouterInstruction, {
        useValue: <any>this._routerInstruction$.map<Match>(set => {
            return {
                locationChange: set.locationChange,
                routes: [...set.routes].slice(1),
                routeParams: set.routeParams,
                queryParams: set.queryParams
            };
        })
    });

    @Input('canDestroy') private _canDestroy: boolean = true;
    @Input('canReuse') private _canReuse: boolean = true;
    @Input('routeName') private _name: string;
    constructor(
        protected _routerInstruction$: RouterInstruction,
        protected _injector: Injector,
        protected _renderer: ComponentRenderer,
        protected _ref: ViewContainerRef,
        private _routing: RoutingService
    ) { }

    ngOnInit() {
        this._sub = (<any>this._routerInstruction$)
            .map(set => {
                const route = set.routes[0];               
                const components = getNamedComponents(route, this.getRealComponentName(this._name));
                console.log(route);
                console.log(components);
                return { route, components };
            })
            .distinctUntilChanged((prev, next) => {
                return prev.components.component === next.components.component
                    && prev.components.loadComponent === next.components.loadComponent && this._canReuse;
            })
            .do(ins => this._cleanPreviousRef())
            .filter(({ components }) => { return (!!components.component || !!components.loadComponent)})
            .switchMap(({ route, components }) => {
                if (this._canDestroy) {

                    return this._renderer.render(route, components, this._injector, this._ref, [this._routerInstructionProvider]);               
                } else {
                    if (this._prev) {
                        this._prev.location.nativeElement.hidden = false;
                        return Observable.of(this._prev);
                        
                    } else {
                        return this._renderer.render(route, components, this._injector, this._ref, [this._routerInstructionProvider]);
                    }
                }
            }
            )
            .subscribe((ref: ComponentRef<any>) => {
                this._prev = ref
            });

    }

    ngOnDestroy() {
        this._cleanPreviousRef();
        this._sub.unsubscribe();
    }

    protected _cleanPreviousRef() {
        if (this._prev) {        
            if (this._canDestroy) {
                this._prev.destroy();
                this._prev = null;
            } else {
                this._prev.location.nativeElement.hidden = true;
            }
        }
    }
    private getRealComponentName(name: string): string {
        let tab = this._routing.actualTabs.filter(x => x.name == name);
        if (tab.length > 0) {
            return tab[0].component;
        } else { return name; }
    }
}`

**Comment by michalstepien** [comment]
I dont know why If click twice on the same route with other query params, they dont create new component and only copy the same previous. Sorry for my english.

**Comment by brandonroberts** [comment]
@michalstepien since the route/query params are observables, we don't need to destroy/recreate the component.
