### ISSUE TITLE
Child/nested route

### ISSUE THREAD

**Issue by benorama** [ngrx/router#130]
Is there any plan to support child/nested router (as it is supported by Angular2 router: https://angular.io/docs/ts/latest/guide/router-deprecated.html#!#child-router)?

Since routes config is not linked to a particular component, I guess that it won't be possible.

**Comment by brandonroberts** [comment]
Yes, you can have nested routes. See the following example.

```
export const routes = [
    {
        path: '/parent',
        component: ParentRouteComponent
        children: [
            {
                path: '/children',
                component: ChildRouteComponent
            }
        ]
    }
]
```

The `ParentRouteComponent` template has a `<route-view></route-view>` that renders its child routes

**Comment by benorama** [comment]
Thanks, I'll give it a try.
Do you think the linkTo router linked will support relative routes for those child routes?
Right now, it looks like only absolute path are supported.

**Comment by brandonroberts** [comment]
For the foreseeable future, only absolute paths are supported. There's nothing stopping you from using a service or a pipe to build a relative path based on the location path though.

**Comment by beljand** [comment]
@brandonroberts how would u use a pipe in [linkTo] directive, do you have any examples?

**Comment by brandonroberts** [comment]
@beljand just using a pipe in general?

```html
<a [linkTo]="'/path' | somePipe">Some Link</a>
```
