### ISSUE TITLE
Compilation error TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.

### ISSUE THREAD

**Issue by galvesribeiro** [ngrx/router#131]
Hey guys,

After npm install on @ngrx packages, app run just fine with the router however, there is an annoying compilation error:

```
12:00:06 AM - File change detected. Starting incremental compilation...
node_modules/@ngrx/core/SyncSubject.d.ts(4,22): error TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.
  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => AnonymousSubscription | Function | void' is not assignable to type '(subscriber: Subscriber<T>) => Subscription'.
      Type 'AnonymousSubscription | Function | void' is not assignable to type 'Subscription'.
        Type 'AnonymousSubscription' is not assignable to type 'Subscription'.
          Property 'isUnsubscribed' is missing in type 'AnonymousSubscription'.
12:00:09 AM - Compilation complete. Watching for file changes.
```

Any ideas on how to get rid of it?

Thanks!

**Comment by Be-ngt-oH** [comment]
Hi,

Have you ugraded rxjs? I've noticed that ngrx/router has a strong dependency on 5.0.0-beta.6 at the moment. If you don't rely on the latest rxjs I think it's best to downgrade back to 5.0.0-beta.6.

It would be nice to update ngrx/router to work with the latest rxjs soon since I've run into a rxjs bug when working with routing parameters.

**Comment by brandonroberts** [comment]
If you're using a version of rxjs other than 5.0.0-beta.6, that's most likely the cause of your issue.

**Comment by galvesribeiro** [comment]
@Be-ngt-oH and @brandonroberts thanks! Just reverted back to .6 and it worked! :)
