### ISSUE TITLE
Non parent guard executed when path is "/"

### ISSUE THREAD

**Issue by ocombe** [ngrx/router#133]
I have the following route definition:

```
import {Routes} from '@ngrx/router';
import {AuthGuard} from "./guards";

const ROUTES: Routes = [
    {
        path: '/',
        guards: [AuthGuard],
        loadComponent: () => new Promise(resolve => {
            (require as any).ensure([], require => {
                resolve(require('./pages/home-page').HomePage);
            });
        })
    }, {
        path: '/login',
        loadComponent: () => new Promise(resolve => {
            (require as any).ensure([], require => {
                resolve(require('./pages/login-page').LoginPage);
            });
        })
    }, {
        path: '/*',
        loadComponent: () => new Promise(resolve => {
            (require as any).ensure([], require => {
                resolve(require('./pages/not-found-page').NotFoundPage);
            });
        })
    }
];

export default ROUTES;
```

When I go to the url "/test" it executes the AuthGuard from "/", this means that "/" is a match for "/test" when checking the guards.
Wether my guard from "/" returns true or false, it goes to the "not found page".
But the thing is that if I remove the guard from "/", then it loads the "not found page" as expected as well.

Which means that it matches the home "/" route, but it doesn't even execute it (the loadComponent method is never run and the HomePage component is not instantiated).

If I try to go the "/login", then here again the AuthGuard from the "/" route is executed for no reason.

**Comment by brandonroberts** [comment]
@ocombe Guards are run on potential route candidates and a top level path of `/` is always considered a candidate. In your guard, you can use the `TraversalCandidate` property `isTerminal` to determine whether the candidate route is the last path in the traversal process and to not run the guard there.

**Comment by ocombe** [comment]
Ok that makes sense, you can probably close this then. And if you can add a small note in the documentation, that would probably help ! :-)

**Comment by brandonroberts** [comment]
Yep! I'll leave this one open until something is added in the docs.
