### ISSUE TITLE
rxjs's take() breaks router subscriptions

### ISSUE THREAD

**Issue by tiagoroldao** [ngrx/router#135]
Using take() on a RouteParams observable breaks routing, as can be seen here -> http://plnkr.co/edit/234YCF?p=preview

This was found to have been fixed by rxjs@5.0.0-beta.8, but it might warrant investigation on how that rxjs bug breaks the router.

Possible related rxjs issue: https://github.com/ReactiveX/rxjs/pull/1705

**Comment by asoldino** [comment]
Hi,

I recently tried ngrx (awesome work!), and definitely encountered the same issue.

Can this be related to? 

lib/router-instruction.ts line 51

```
create(): RouterInstruction {
    return this._locationChanges$
      .observeOn(asap)
      .distinctUntilChanged((prev, next) => prev.path === next.path)
      .let(composeHooks(this._routerHooks))
      .switchMap(change => this._traverser.find(change))
      .filter(match => !!match)
      .let(composeHooks(this._instructionHooks))
      .enterZone(this._ngZone)
      .publishReplay(1)
      .refCount();  // => The take probably makes the refCount go to zero for some reason
  }
```

**Comment by Be-ngt-oH** [comment]
Hi,

the bug is related to a bug in the implementation of reference counting observables. As @tiagoroldao stated this bug is already fixed in the latest rxjs.
I've encountered this bug as well and used `share()` as a workaround.
```
        this.queryParams
            // TODO: Calling share is needed due to a bug in rxjs.
            // Remove this workaround when we're >= 5.0.0-beta.8
            .share()
            .take(1)
```
Note: Bug is present in queryParams as well as routerParams.
