### ISSUE TITLE
Default path redirect?

### ISSUE THREAD

**Issue by mrchops1024** [ngrx/router#141]
I can't figure out how to have the typical '/' path redirect to something. I don't particularly need a landing page on my current app, so I want to redirect to a particular route if they have access. Here is my route config:

```
export const routes: Routes = [
    {
        path: '/',
        redirectTo: '/user/add',
    },
    {
        path: '/user/add',
        guards: [ AuthGuardLevel1 ],
        component: AdduserComponent
    },
    {
        path: '/user/update',
        guards: [ AuthGuardLevel2 ],
        component: UpdateuserComponent
    },
    {
        path: '/unauthorized',
        component: UnauthorizedComponent
    },
    {
        path: '/**',
        component: NotfoundComponent
    },
]
```

This is what I get in the console when navigating to '/':

`zone.js:260 Uncaught TypeError: pathToRegexp.compile is not a function`

I'm sure I'm missing something simple, but I haven't figured it out yet.

**Comment by MikeRyan52** [comment]
Sounds like you might be using the angular-cli. If that's the case, there's a dependency conflict that you can resolve by installing `path-to-regexp` manually:

```bash
npm i path-to-regexp --save
```

**Comment by mrchops1024** [comment]
That did the trick, thanks!
