### ISSUE TITLE
How to share a service(only one instance) across multiple routes

### ISSUE THREAD

**Issue by medigvijay** [ngrx/router#143]
What should be the approach to share an application level service to share across different routes, which are not loaded at the same time. Basically I just want to have only one instance of the service across different routes.
Apparently to me it seems like, including a service in root component makes it available only to direct and nested (and already loaded)components. 

Thanks

**Comment by brandonroberts** [comment]
If you provide the service at the bootstrap level or the app component level it will be shared amongst all the child components, including the routes as long as you don't include it it in any `providers` of your components.
