### ISSUE TITLE
RouterParams Get Triggered On Each Load

### ISSUE THREAD

**Issue by rsnider19** [ngrx/router#144]
I am trying to user my `RouterParams` to trigger API calls like so:
```
constructor(private routeParams: RouteParams, private userService: UserService) {
    routeParams.pluck<number>('id')
      .subscribe(id => {
          this.userService.getUserDetails(id);
          this.userService.getUser(id);
      });
}
```
This works great, but every time I navigate away from this component, the subscription gets triggered again for the new route. In other words, if I am on `'User/19'`, I get 19 upon loading the component. When I navigate to `'/'`, this gets triggered again, except `id` is undefined.

I also noticed that when navigating to `'User/19'`, then to `'/'`, then back to `'User/19'`, the first `subscribe` still kicks in, so this code gets triggered twice.

I am not sure if I am using this and thinking about it incorrectly, or if this is a bug. I did notice that if I do what is shown in the `RouteParams` example by assigning the `post$` variable and using an async pipe, none of the above issues occur.

**Comment by brandonroberts** [comment]
This is intended behavior. You need to store the subscription in a class variable and unsubscribe in your ngOnDestroy method, for when you navigate away. The async pipe does this for you which is why the results were different.

**Comment by rsnider19** [comment]
I thought I had tried that, but I think I recall it triggering before the ngOnDestroy when navigating away. I'll try again when I get home tonight. Thanks for the quick reply @brandonroberts!

**Comment by rsnider19** [comment]
@brandonroberts solution works as expected
