### ISSUE TITLE
LINK_ACTIVE_OPTIONS no exported member

### ISSUE THREAD

**Issue by beljand** [ngrx/router#145]
`import {LINK_ACTIVE_OPTIONS} from '@ngrx/router';`

There is no exported member 'LINK_ACTIVE_OPTIONS'

**Comment by brandonroberts** [comment]
Its not in the latest beta(1). When we do another release it will be there.

**Comment by brandonroberts** [comment]
Closed via https://github.com/ngrx/router/commit/4327865f98ff9a54841f9b171f5ec1eb9fcba431 
Will be ready once beta-2 is published.
