### ISSUE TITLE
How to get current route

### ISSUE THREAD

**Issue by wambowams** [ngrx/router#146]
Is there a way to query the current route, like the way you can query the route params?

**Comment by beljand** [comment]
`import { RouteParams } from '@ngrx/router';`

`constructor(
        private _routeParams: RouteParams
)`

`this._routeParams.subscribe(data => data)`

**Comment by wambowams** [comment]
In this way I only can get the Route-Params if I have defined some.
If I have for example this Routes:

```
export const routes: Routes = [
  {
    path: '/',
    component: StartComponent
  },
  {
    path: '/statistik',
    component: StatistikComponent
  }
];

```
An I´m at localhost/statistiken then I want to get "statistiken".

**Comment by beljand** [comment]
"statistik" is not a routeParam, a routeParam would be something like
`
{
    path: '/:id',
    component: StatistikDetailComponent
 }
`
so
`/statistik/123`

**Comment by beljand** [comment]
You can also take a look at 'RouterInstruction'

`import { RouterInstruction } from '@ngrx/router';`

It will get you the whole route config

**Comment by wambowams** [comment]
OK thank you, I will have a look at "Routeinstruction"
