### ISSUE TITLE
Property 'pluck' does not exist on type 'QueryParams'.

### ISSUE THREAD

**Issue by brandonreid** [ngrx/router#152]
Trying to implement the "Using QueryParams" example from the (documentation)[https://github.com/ngrx/router/blob/master/docs/overview/params.md].

I've updated the `@ngrx/router` dependency. Any ideas?

Thanks in advance!

**Comment by r-park** [comment]
You need to import the pluck operator:

`import 'rxjs/add/operator/pluck';`
