### ISSUE TITLE
[Question] Does ngrx router allow adding components to route-view of parent components 

### ISSUE THREAD

**Issue by LisaTatum** [ngrx/router#154]
I was trying the angular 2 router3 but I am disappointed.

http://stackoverflow.com/questions/38192020/how-to-render-the-child-route-into-the-router-outlet-of-the-parents-parent?noredirect=1#comment63815303_38192020

Can ngrx router do what I need?

**Comment by brandonroberts** [comment]
Yes, all your components can be in named route-views if that's what you're seeking.

**Comment by LisaTatum** [comment]
Fine then I will try your router! and not the ng2 ui-router :-)
