### ISSUE TITLE
Can you pass data to child routes and index components?

### ISSUE THREAD

**Issue by danielcrisp** [ngrx/router#155]
I think my question is similar to this guys' question:

http://stackoverflow.com/questions/37796352/how-to-pass-data-from-parent-route-to-child-route-in-ngrx-angular2

Basically I have this route configuration:

```javascript
   ...
   },  {
            path: '/event',
            component: IndexComponent, // generic index component
            index: {
                redirectTo: '/' // we must have an ID
            },
            children: [{
                path: ':id',
                component: EventComponent, // data is loaded here
                index: {
                    component: EventFormComponent // and I want to access here
                },
                children: [{
                    path: '/menu',
                    component: EventMenuEditComponent // and here
                }, {
                    // and so on
                }]
            }]

    }, {
    ...
```

Resulting in URLs like this:

`/event/1234567890` = `EventComponent` + `EventFormComponent`
`/event/1234567890/menu` = `EventComponent` + `EventMenuEditComponent`
`/event/1234567890/users` = `EventComponent` + `EventUsersComponent`
etc

My `EventComponent` loads the event details from an API endpoint and I want to be able to share the data with all child routes AND the index component (`EventFormComponent`).

The `EventFormComponent` displays a form where the user can edit the event details.

Normally I would just add the data to the component's attribute, and then access it using `@Input()`, e.g.

    <event-form [data]="myData"></event-form>

But, of course, I never actually write `<event-form></event-form>` because the router handles this for me.

Is there some way of doing this within ngrx router or should I use a service to store / access the data?

**Comment by danielcrisp** [comment]
I've worked around this now by creating a shared data service, but I'd be interested to know if there is a different way to do this with the router...?

**Comment by brandonroberts** [comment]
A shared service is the most common way. If you were using ngrx/store you would push that data into the store so it could be accessed by whichever components needed it.

**Comment by danielcrisp** [comment]
Thanks Brandon, I'll take another look at ngrx/store
