### ISSUE TITLE
Correct way to get multiple route params

### ISSUE THREAD

**Issue by danielcrisp** [ngrx/router#157]
I have two route params in my url:

`/event/[eventId]/survey/[surveyId]`

I know how to get each param individually, but is it possible to get both at the same time?

It looks like it should be possible - https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/pluck.md

However it doesn't seem to work.

This works:
```javascript
    routeParams$.pluck('eventId').subscribe(val => console.log(val));
```
As does this:
```javascript
    routeParams$.pluck('surveyId').subscribe(val => console.log(val));
```
But this returns `undefined`:
```javascript
    routeParams$.pluck('eventId', 'surveyId').subscribe(val => console.log(val));
```

**Comment by MikeRyan52** [comment]
Using pluck with multiple strings is for going _deep_ into a nested object like this:

```js
{
  eventId: {
    surveyId: { }
  }
}
```

Instead, I'd recommend using the `select` operator along with `combineLatest`:
```ts
import '@ngrx/core/add/operator/select';
import { combineLatest } from 'rxjs/observable/combineLatest';

combineLatest( routeParams$.select('eventId'), routeParams$.select('surveyId') )
  .subscribe(([ eventId, surveyId ]) => {

  });
```

**Comment by danielcrisp** [comment]
Thanks Mike

In my version of RxJS (v5.0.0-beta.6) I can't import `combineLatest` using your example. It looks like they've moved or removed it.

I didn't choose this version, it is a peer dependancy of ngrx.

Any ideas?

**Comment by r-park** [comment]
Try this:
```js
import 'rxjs/add/observable/combineLatest';
```

**Comment by danielcrisp** [comment]
Ok I figured it out, thanks to a deleted comment by Richard Park.

I had to add this:

```javascript
import 'rxjs/add/observable/combineLatest';
```

And then use the `combineLatest` method on the `Observable`, like this:

```javascript
import '@ngrx/core/add/operator/select';
import 'rxjs/add/observable/combineLatest';

Observable.combineLatest( routeParams$.select('eventId'), routeParams$.select('surveyId') )
    .subscribe(([ eventId, surveyId ]) => {
        console.log(eventId, surveyId);
    });
```

If this is ok you can close this. Thanks for your help
