### ISSUE TITLE
[question] named route-system

### ISSUE THREAD

**Issue by akomm** [ngrx/router#160]
Is there a reason why links are not generated from named routes, instead you have to explicitly use a path? This has the problem that if you change the path in your route config, you have to change it everywhere in your templates.

Is there a reason, why You don't use something like this:
```ts
type RouteName = string|string[];

interface RouteParams {
  [param: string]: string;
}

interface Match {
  routeParams: RouteParams;
  routes: Routes;
}

interface Router {
  matchRoute(url: string): Match;
  generateUrl(routeName: RouteName, routeParams?: RouteParams): string;
}
```
*note: routeName could also be a dot-separated syntax, or something similar instead or string-array to describe a path inside a route-tree*

linking could look something like that:
```html
<a [linkTo]="['article', 'post', {articleId: 15, postId: 20}]">link</a>
```

Route config could look like that:
```ts
export const appRoutes: Routes = [
  {
    name: 'article',
    path: 'articles/:articleId',
    component: ArticleViewCmp,
    children: [
      {
        name: 'post',
        path: 'post/:postId',
        component: PostViewCmp
      }
    ]
  },
];
```

**linkTo** could use the `Router.prototype.generateUrl`- api to make the url. Url string can be reversed into routes via  `Router.prototype.matchRoute`.

**Comment by MikeRyan52** [comment]
@ngrx/router (and now @angular/router) emphasizes lazy loading of components and routes as a primary use case. Unfortunately, this directly conflicts with named routes. If you try to generate a link to a name route but the router hasn't lazily loaded that code yet, how can we generate links? The answer is we can't, and we definitely don't want link loading to trigger lazy loading.

Additionally, @brandonroberts and I evaluated the history of large Angular 1 applications we had worked on and found that we were _rarely_ changing the paths of our routes. In fact, we were changing route names just as often as we were changing paths. This meant we were not actually realizing the refactoring benefits of a named route system.

The limitation of named routes with lazy loading in addition to our use case studies on the feature led us to designing this router without named routes. We will not support this feature in the future, either.

Hopefully that clears it up for you.
