### ISSUE TITLE
Question: Detecting a route unloading without ngOnDestroy?

### ISSUE THREAD

**Issue by jasoninrapid** [ngrx/router#161]
I have a route that displays people: `/people`, and have another route for creating a person: `/people/create`.  When the user hits the back button in the browser while in `/people/create` I would like to be able to detect that the route is unloading so that I might do some work.  I think I would typically do this by implementing the OnDestroy interface and putting my cleanup code in ngOnDestroy, but that doesn't seem to work with the ngrx router.  Is there a similar hook for the ngrx router (I cannot find it)?  ie:

    ngrxOnUnload() {
        //do some fantastically interesting cleanup work, like hiding a modal
    }

#

**Comment by danielcrisp** [comment]
I use `ngOnDestroy` for exactly the purpose you describe and it's working for me... perhaps you have some issue elsewhere?
