### ISSUE TITLE
Limit parameter length or a way to show a custom 404?

### ISSUE THREAD

**Issue by Flood** [ngrx/router#165]
I have a route config like this

`{
		path: ':lang/',
		components: {
			main: HomeComponent
		}
	},`

But let's say that I have a custom 404 page. 

`{
		path: '404',
		components: {
			main: NotFoundComponent
		}
	},
	{
		path: '**',
		redirectTo: '/404'
	}
}`

When entering example.com/404...it shows me the HomeComponent since it beleive the 404 is a lang parameter. How can I do this the correct way? Is there a way to limit the lang parameter to only two characters?

**Comment by brandonroberts** [comment]
S your 404 path to `404` instead of `:404`

**Comment by Flood** [comment]
@brandonroberts Sorry, that was a typo.

**Comment by brandonroberts** [comment]
Ok. Route order matters, so just move the `404` route above the `:lang` route and it should work

**Comment by Flood** [comment]
Oh great, that works! Thanks
