### ISSUE TITLE
Create example apps using ngrx/router

### ISSUE THREAD

**Issue by MikeRyan52** [ngrx/router#31]
We need to start thinking about building example apps for the router. While they will be good reference material for new users, the main benefit is having a solid target for e2e tests.

For reference, here are the examples react-router keeps maintained: https://github.com/reactjs/react-router/tree/master/examples

**Comment by fxck** [comment]
I want to use it in the example refractor, along the dev tools, it should demonstrate most of the use cases. I'm just waiting for material alpha 2 to land. 

-- 
Ales Rechtorik

**Comment by Krisa** [comment]
Regarding examples and/or documentation, I would be happy that someone highlights the advantages or use cases going with this approach over the native router. While this feels indeed relatively similar to how ReactRouter is working, the advantage is, at least for me, not obvious at first.

**Comment by fxck** [comment]
https://github.com/fxck/ngrx-example

and to quote Brandon

> the main differences between the component router and ngrx/router are the decisions behind the design. The component router takes a more internal approach when it comes to components if you look at the lifecycle hooks. Our router doesn’t require that the router hook into your components so any component is routable. Another difference is the use of observables. The component router uses promises to handle its lifecycle, whereas ours uses observables because they lend themselves to more of a reactive approach. Our route/query parameters are observable which makes reusing components when parameters change easier. Our router has more streams available for you to subscribe to and react upon. The overall idea is that the browser URL itself is a stream and we are turning that stream into a view of rendered routes. Both routers have a concept of lazy loading, protecting routes, resolving data and lifecycle events. Both still have gaps that need to be filled. If you prefer a more observable approach, our router works very nicely with that.

**Comment by dmackerman** [comment]
I think it's also important that there are examples on how to integrate this with the Angular CLI. I'm actually running into some errors that I'm trying to work through right now. Appears that `query-string` is maybe not being referenced properly, or has to be installed manually.

https://github.com/ngrx/router/blob/master/lib/route-traverser.ts#L16

**Comment by MikeRyan52** [comment]
@dmackerman Agreed. I recently started building some sample apps with the CLI and found configuring it to work with the router was very difficult.

If you want a very rough example of the configuration, [see here](https://github.com/MikeRyan52/jubilant-octo-sniffle/blob/master/src/system-config.ts#L81) and [here](https://github.com/MikeRyan52/jubilant-octo-sniffle/blob/master/angular-cli-build.js#L15)

**Comment by dmackerman** [comment]
@MikeRyan52 thanks a bunch for the examples, I got everything running. Might be a good idea to add that stuff to a wiki entry - however clumsy it may be.

**Comment by nicolaveritas** [comment]
@MikeRyan52 I have the same errors of @dmackerman on `query-string` and `path-to-regex` 
but config from [here](https://github.com/MikeRyan52/jubilant-octo-sniffle) doesn't work for me and actually that repo falls into the same exact errors

**Comment by MikeRyan52** [comment]
We've added documentation covering how to configure ngrx/router if you are using SystemJS. See here: https://github.com/ngrx/router/blob/master/docs/overview/systemjs.md
