### ISSUE TITLE
Break Location Service Up

### ISSUE THREAD

**Issue by MikeRyan52** [ngrx/router#47]
Currently the `Location` service has a number of responsibilities:

1. Listen for History `popstate` events
2. Allow users to traverse history with `back()` and `forward()`
3. Parse the current URL into pathname and query string
4. Dispatch new path changes
5. Prepare external URLs

Going forward, we'll be splitting these into three separate services:

`History` will listen for popstate events mapping them into `LocationChange` events. In addition, users can traverse history using `back()` and `forward()`
```ts
class History extends Observable<LocationChange> {
  back();
  forward();
}
```

`Location` will provide the current query, pathname, and hash. It will also normalize and prepare external URLs:
```ts
class Location {
  pathname: string;
  search: string;
  hash: string;

  normalize(url: string);
  prepareExternalUrl(url: string, query: string);
}
```

`Router` will be responsible for dispatching location changes (though the act of actually handling them will be done via middleware):
```ts
class Router extends Observable<LocationChange> {
  go(path: string, query: any = '');
  replace(path: string, query: any = '');
  search(query: any = '');
}
```

cc @brandonroberts

**Comment by laurelnaiad** [comment]
sweet! Some good fodder for middleware here..

**Comment by MikeRyan52** [comment]
Now that the Location services have been broken out from the component router in Angular 2, we'll need a new strategy here.
