### ISSUE TITLE
Angular RC compatiblity

### ISSUE THREAD

**Issue by tamascsaba** [ngrx/router#84]
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by fxck** [comment]
https://github.com/ngrx/router/tree/ngconf

**Comment by tamascsaba** [comment]
thx, the really really really quick answer :)

**Comment by MikeRyan52** [comment]
Yup, we're navigating some of the breaking changes and should be able to release an RC compatible release soon! 👍

**Comment by tamascsaba** [comment]
nice :+1: I am really looking forward to.
