### ISSUE TITLE
RouteParams & QueryParams typings

### ISSUE THREAD

**Issue by tamascsaba** [ngrx/router#95]
Very simple examle:
```
params.pluck('id').map((id) => {
      this.getSession(id);
});
```

```
getSession(id: string) {
}
```

```
 Error TS2345: Argument of type '{}' is not assignable to parameter of type 'string'.
```

**Comment by MikeRyan52** [comment]
Two reasons why this won't work:

1. We don't actually know the shape of the params object until runtime, so there's not a good type to describe it
2. `pluck('id')` can't be well typed _anyways_ since the string selector isn't known

Solution would be to explicitly type `pluck()`:

```ts
params$.pluck<string>('id')
```

**Comment by tamascsaba** [comment]
Thx :+1
