### ISSUE TITLE
guards apply run twice 

### ISSUE THREAD

**Issue by tamascsaba** [ngrx/router#98]
![guards](https://cloud.githubusercontent.com/assets/3479963/15217199/b5c9d438-185a-11e6-8489-1f0b0260ffec.png)

When I use guards like:
```
  protectRoute(candidate: TraversalCandidate) {
    return this.http
      .get('/api/authentication')})
      .map(() => true)
      .catch(() => {
        this.router.go('/login');
        return Observable.of(false);
      });
  }
```

My route config:
```
export const routes: Routes = [
  {path: '/', component: DashboardPage, , guards: [AuthGuardService]},
  {path: '/login', component: LoginPage},
];
```

ngrx/router/guard.ts run twice the candidate callback
```
return return route$.mergeMap(candidate => {...})
```

I don't know why, any idea?

**Comment by tamascsaba** [comment]
When I add AuthGuardService to more routes, like this:
```
const routes: Routes = [
  {path: '/', component: DashboardPage, guards: [AuthGuardService]},
  {path: '/dashboard', component: DashboardPage, guards: [AuthGuardService]},
  {path: '/login', component: LoginPage},
  {path: '/404', component: NotFoundPage},
  {path: '/foo', component: FooPage, guards: [AuthGuardService]},
  {path: '/foo/:id', component: FooDetailsPage, guards: [AuthGuardService]},
  {path: '/**', component: NotFoundPage}
];
```
```'/'``` run 2 times
```'/dashboard'``` 4 times
```'/foo'``` 4 times
```'/foo/:id'``` 6 times

![guards](https://cloud.githubusercontent.com/assets/3479963/15217824/8f259508-185d-11e6-90c0-59557240416c.png)

**Comment by fxck** [comment]
try using .take(1)

**Comment by tamascsaba** [comment]
Not work :(
```
  protectRoute(candidate: TraversalCandidate) {
    return this.http
      .get('/api/authentication')
      .take(1)
      .map(() => true)
      .catch(() => {
        this.router.go('/logout');

        return Observable.of(false);
      });
  }
```

**Comment by brandonroberts** [comment]
@tamascsaba can you reproduce in a plunker? I'm not seeing it here: http://plnkr.co/edit/drg4oc?p=preview

**Comment by brandonroberts** [comment]
@tamascsaba are you still having this issue? If not we can close this issue.

**Comment by tamascsaba** [comment]
I will make an example with my webpack enviroment soon as possible.

**Comment by brandonroberts** [comment]
Ok

**Comment by brandonroberts** [comment]
A better option in this situation would be to use a pathless route with a guard and put your routes under it. A guard should only run when it reaches a potential candidate, so I'd still like to the see that reproduced.

```ts
const routes: Routes = [
  {path: '/', component: DashboardPage},
  {path: '/login', component: LoginPage},
  {path: '/404', component: NotFoundPage},
  {
    component: AuthComponent,
    guards: [AuthGuardService],
    children: [
      {path: '/dashboard', component: DashboardPage},
      {path: '/foo', component: FooPage},
      {path: '/foo/:id', component: FooDetailsPage}
    ]
  },
  {path: '/**', component: NotFoundPage}
];
```

**Comment by tamascsaba** [comment]
I creted a sample repo: https://github.com/tamascsaba/router-playground
When click any 'Denied' link check.json loading twice.

**Comment by brandonroberts** [comment]
Ok, the issue isn't with the guards, its with your providers. the `providerRouter` function includes the ROUTER_PROVIDERS. You are also including `...ROUTER_PROVIDERS` in your `src/platform/browser/providers.ts` file. If you remove that, it works as designed and the guards are only fired once.

**Comment by brandonroberts** [comment]
I used this as an example of a pathless route to group the routes together.

```
import {Routes} from '@ngrx/router';

import {Home} from '../_home';
import {About} from '../_about';
import {Denied} from '../_denied';

import {AuthGuard} from './auth-guard';
import {Component} from '@angular/core';

@Component({
  selector: 'auth',
  template: '<route-view></route-view>'
})
class Auth{}

export const routes: Routes = [
  {path: '/', component: Home},
  {path: '/about', component: About},
  {
    component: Auth,
    guards: [AuthGuard],
    children: [
      {path: 'denied', component: Denied},
      {path: 'same-denied', component: Denied}
    ]
  }
];
```

**Comment by tamascsaba** [comment]
thx :+1:
